### PR TITLE
Updated to account for new source format

### PR DESCRIPTION
**Pull request by MLBZ521**
Content is now distributed as a .app within a .zip (no longer pre-packaged)
- Removed the unpacking steps
+ Create package with the extracted app

### CODE REVIEW

**Comment by MLBZ521** [comment]
@tbridge Just wanted to follow up on the PR and see if it could be merged?  Thanks!

**Comment by MLBZ521** [comment]
@tbridge Just bumping and tagging for visibility.

**Comment by tbridge** [comment]
Sorry @MLBZ521 ! All set.

**Comment by MLBZ521** [comment]
No worries, thank you!

**Pull request merged**
